---
- name: Re-create a prometheus container
  docker_container:
    name: {{ prometheus_name }}
    image: {{ prometheus_image }}
    state: present
    recreate: yes
    exposed_ports:
      - "{{ prometheus_port_externe }}:{{ prometheus_port_externe }}"
    volumes_from:
      - {{ prometheus_volume }}